# -*- coding: utf-8 -*-
"""one _hot_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVVojWPTFj5JM6Mg9jFgtmACD-_wEQQt

**Codificación one hot encoding para valores nominales**
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

#importar datos

test = pd.read_csv('/content/drive/MyDrive/ArchivosColab/test.csv')
train = pd.read_csv('/content/drive/MyDrive/ArchivosColab/train.csv')

train.head()

train.info()

# Como se distribuyen los valores numericos
train.describe()

#codificación one-hot encoding para las variables categóricas "Sex" y "Embarked"
one_hot_encoded_data = pd.get_dummies(train, columns = ['Sex','Embarked'])
one_hot_encoded_data.head()